version : '2'
networks:
  pns-network:

services:
  nginx:
      image: nginx:alpine
      ports:
        - "8805:80"
      volumes:
        - ./site.conf:/etc/nginx/conf.d/default.conf
        - ./:/app
      networks:
        - pns-network
  php:
      build:
        context: .
      volumes:
        - ./:/app
        - /app/vendor
      networks:
        - pns-network
